version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    assignees:
      - davidsandoz
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    # Ignoring @nuxtjs/i18n because of issues with defineI18nRoute
    # https://github.com/nuxt-modules/i18n/issues/3784
    ignore:
      - '@nuxtjs/i18n'
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - davidsandoz
    assignees:
      - davidsandoz
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
